version: '3.9'
services:
  backend:
    build: ./backend
    image: skytracker:backend
    expose:
      - 8000
    networks:
      - backend
    develop:
      watch:
        - action: rebuild
          paths:
            - ./backend

  frontend:
    build: ./frontend
    image: skytracker:frontend
    environment:
      BACKEND_URL: http://backend:8000
    ports:
      - "80:80"
    networks:
      - backend
    develop:
      watch:
        - action: rebuild
          paths:
            - ./frontend

networks:
  backend:
    name: backend

  